productos = [
    {
        'id': 1,
        'modelo': 'Guitarra Acústica',
        'marca': 'Ibanez',
        'descripcion': 'La guitarra acústica de Ibanez es un instrumento versátil y de alta calidad, perfecto para los amantes de la música folk, el rock acústico y otros estilos acústicos. Cuenta con un sonido cálido y resonante, una construcción duradera y un diseño clásico.',
        'foto': 'img/guitarra_agustica.png',
        'precio': '$300.000',
    },
    {
        'id': 2,
        'modelo': 'Piano Digital',
        'marca': 'Yamaha',
        'descripcion': 'El piano digital de Yamaha ofrece una experiencia de interpretación auténtica con una sensación similar a la de un piano acústico tradicional. Cuenta con teclas ponderadas, múltiples voces de instrumentos y opciones de conectividad avanzadas para satisfacer las necesidades de los pianistas de todos los niveles.',
        'foto': 'img/piano.png',
        'precio': '$1.200.000',
    },
    {
        'id': 3,
        'modelo': 'Batería Electrónica',
        'marca': 'Roland',
        'descripcion': 'La batería electrónica de Roland es perfecta para los bateristas que buscan practicar en casa sin hacer ruido. Ofrece una amplia variedad de sonidos de batería realistas, almohadillas sensibles al tacto y la posibilidad de conectar auriculares para una experiencia de juego silenciosa.',
        'foto': 'img/bateria_electronica.png',
        'precio': '$800.000',
    },
    {
        'id': 4,
        'modelo': 'Teclado MIDI',
        'marca': 'Novation',
        'descripcion': 'El teclado MIDI de Novation es una herramienta esencial para la producción musical y la creación de música electrónica. Ofrece teclas sensibles a la velocidad, perillas y pads asignables, y una integración perfecta con software de producción musical como Ableton Live.',
        'foto': 'img/teclado_midi.png',
        'precio': '$250.000',
    },
    {
        'id': 5,
        'modelo': 'Saxofón Alto',
        'marca': 'Yamaha',
        'descripcion': 'El saxofón alto de Yamaha es un instrumento de viento versátil que se utiliza en una amplia variedad de géneros musicales, desde jazz hasta música clásica. Cuenta con una construcción de alta calidad, llaves ergonómicas y un sonido cálido y expresivo.',
        'foto': 'img/saxofon_alto.png',
        'precio': '$1.500.000',
    },
    {
        'id': 6,
        'modelo': 'Violín',
        'marca': 'Stradivarius',
        'descripcion': 'El violín Stradivarius es un instrumento legendario conocido por su artesanía excepcional y su calidad de sonido inigualable. Cada violín es único y hecho a mano por expertos luthiers. Es la elección perfecta para los violinistas profesionales y aficionados serios que buscan un instrumento de alta gama.',
        'foto': 'img/violin.png',
        'precio': '$350.000',
    },
    {
        'id': 7,
        'modelo': 'Trompeta',
        'marca': 'Bach',
        'descripcion': 'La trompeta Bach es ampliamente reconocida por su calidad y sonido brillante. Es un instrumento utilizado en diversos estilos musicales, como jazz, música clásica y bandas de música. Con una construcción sólida y una respuesta rápida, la trompeta Bach ofrece un rendimiento excepcional para músicos de todos los niveles.',
        'foto': 'img/trompeta.png',
        'precio': '$1.200.000',
    },
    {
        'id': 8,
        'modelo': 'Bajo Eléctrico',
        'marca': 'Fender',
        'descripcion': 'El bajo eléctrico de Fender es un instrumento esencial para los bajistas de rock, funk y otros estilos musicales. Ofrece un sonido potente y profundo, junto con una gran comodidad de ejecución. Con su diseño icónico y su calidad de construcción confiable, el bajo eléctrico de Fender es una opción popular entre los músicos de bajo.',
        'foto': 'img/bajo_electrico.png',
        'precio': '$900.000',
    },
    {
        'id': 9,
        'modelo': 'Flauta Travesera',
        'marca': 'Yamaha',
        'descripcion': 'La flauta travesera de Yamaha es un instrumento de viento madera con un sonido cálido y melodioso. Es popular en música clásica, bandas y conjuntos de música folclórica. Con una construcción duradera y un diseño ergonómico, la flauta travesera de Yamaha ofrece una gran respuesta y facilita la interpretación para flautistas de todos los niveles.',
        'foto': 'img/flauta_travesera.png',
        'precio': '$800.000',
    },
    {
        'id': 10,
        'modelo': 'Guitarra Eléctrica',
        'marca': 'Gibson',
        'descripcion': 'La guitarra eléctrica Gibson es un ícono en el mundo de la música. Con su sonido poderoso y característico, es la elección preferida de guitarristas de rock y blues. Cuenta con una construcción de alta calidad, pastillas versátiles y un diseño elegante que la convierten en una opción de primer nivel para los amantes de la guitarra eléctrica.',
        'foto': 'img/guitarra_electrica.png',
        'precio': '$2.500.000',
    },
    {
        'id': 11,
        'modelo': 'Piano de Cola',
        'marca': 'Steinway & Sons',
        'descripcion': 'El piano de cola Steinway & Sons es sinónimo de excelencia en la fabricación de pianos. Reconocido por su tono rico y su respuesta sensible, este piano es la elección preferida de muchos pianistas profesionales y salas de conciertos. Cada piano de cola Steinway & Sons es una obra maestra cuidadosamente construida que ofrece una experiencia musical incomparable.',
        'foto': 'img/piano_cola.png',
        'precio': '$12.000.000',
    },
    {
        'id': 12,
        'modelo': 'Batería Acústica',
        'marca': 'Pearl',
        'descripcion': 'La batería acústica de Pearl es una elección popular entre bateristas de todos los niveles. Con su construcción robusta y sonido potente, ofrece una experiencia de percusión emocionante. Equipada con tambores de alta calidad y herrajes duraderos, la batería acústica de Pearl garantiza un rendimiento excepcional en cualquier estilo musical.',
        'foto': 'img/bateria_acustica.png',
        'precio': '$2.000.000',
    },
]
