# Generated by Django 4.2.2 on 2023-06-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_venta', '0004_alter_venta_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='hora_venta',
            field=models.TimeField(auto_now=True),
        ),
    ]
