# Generated by Django 4.2.2 on 2023-06-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_venta', '0005_venta_hora_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
