# Generated by Django 4.2.2 on 2023-06-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_venta', '0006_alter_producto_precio_alter_venta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.PositiveIntegerField(),
        ),
    ]
