# Generated by Django 4.2 on 2023-07-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_venta', '0007_alter_detalleventa_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
