# Generated by Django 4.2 on 2023-07-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_venta', '0008_alter_detalleventa_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=True, upload_to='assets/img/'),
        ),
    ]
